version: "3.7"
services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: mcabank-db
    ports:
      - "3306:3306"
    volumes:
      - .database:/var/lib/mysql

  localstack:
    image: localstack/localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=sqs
      - DEFAULT_REGION=eu-west-1
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test

  jaeger:
    image: cr.jaegertracing.io/jaegertracing/jaeger:2.10.0
    container_name: jaeger
    ports:
      - "16686:16686" 
      - "4317:4317"   
      - "4318:4318"   
      - "5778:5778"   
      - "9411:9411"   
